#!/usr/bin/php
<?php
/**
 * Warm a Magento Full Page Cache.
 * This assumes you have an FPC installed on the target site.
 * If you don't all it will do is create undue load on your server.
 * All the script does is download your sitemap.xml file and hit every url in the list.
 * 
 * In reality this script will work on any site that provides a sitemap.xml file.
 * Please don't use the script to attack websites! Frankly, it won't even work well as
 * a DOS attack, because it executes each request synchronously.
 *
 * Copyright Nathan Nobbe 2015.
 */

// Load the backend class
require './MageCacheWarmer.php';

if($argc < 2) {
    usage();
}

$sMode  = $argv[1];
$sFunc  = 'warm';
$iDelay = 0;
switch($argv[1]) {
    case '-h' : usage(); break;
    case '-t' :
        if($argc > 3) {
            usage();
        }

        $sFunc = 'test';
        $sUrl  = $argv[2];
        break;
    case '-w':
        if($argc < 3 || $argc > 4) {
            usage();
        }

        if($argc == 3) {
            $sUrl = $argv[2];
        }
        elseif($argc == 4) {
            list($option, $seconds) = explode('=', $argv[2]);
            $iDelay = 0;
            if($option != '-d' || (int)$seconds < 1) {
                echo 'Warning: Unrecognized option ' . $argv[3] . PHP_EOL;
            } else {
                $iDelay = $seconds;
            }

            $sUrl = $argv[2];
        }
        break;
    default:
        usage();
}

try {
    $oMageCacheWarmer = new MageCacheWarmer($argv[2], 'echoCallback');
    $fSpeedup         = $oMageCacheWarmer->loadSitemap()->$sFunc();

    if($sFunc == 'test') {
        reportResults($oMageCacheWarmer->getAvgDownloadTime(), true);
    } else {
        reportResults($oMageCacheWarmer->getAvgDownloadTime());
        echo 'Speedup is ' . $fSpeedup . '%' . PHP_EOL; 
    }
} catch(Exception $e) {
    echo "Cache warmer crashed with error: " . PHP_EOL;
    echo $e->getMessage();
    exit(1);
}

/**
 * echo messages from the underlying class.
 */
function echoCallback($sMsg)
{
    echo $sMsg;
}

/**
 * Report the results
 */
function reportResults($fAvgTime, $bTest=false)
{
    $sFinishType = $bTest ? 'testing' : 'warming';

    echo "Finished $sFinishType your Magento site performance" . PHP_EOL;
    echo 'Average page time (in milliseconds): ' . $fAvgTime . PHP_EOL;
}

/**
 * Print the script usage and exit.
 */
function usage()
{
    echo '-------------------------------------' . PHP_EOL;
    echo 'wfpc - Magento full page cache warmer' . PHP_EOL;
    echo '-------------------------------------' . PHP_EOL . PHP_EOL;
    echo 'wfpc <-h|-t|-w> [-d=delay] <sitemap url>' . PHP_EOL . PHP_EOL;
    echo 'Run help to see the usage options                       : wfpc -h' . PHP_EOL;
    echo 'Run wfpc in test mode to get an idea of page performance: wfpc -t <sitemap url>' . PHP_EOL;
    echo 'Warm the Magento cache                                  : wfpc -w [-d=delay] <sitemap url>' . PHP_EOL . PHP_EOL;
    echo 'The last form of the command allows a -d option to place a pause of X number of seconds between request' . PHP_EOL;
    exit();
}
